### ISSUE TITLE
Request for Visual AntMaze and Roboverse Code.

### ISSUE THREAD

**Issue by qortmdgh4141** [seohongpark/HIQL#4]
Hello, I hope this message finds you well. 

I noticed in the GitHub Issues that you had generously offered to share the **Visual AntMaze** and **Roboverse** code to other researchers. I am very interested in exploring these environments for my own research.

**Could you kindly send the relevant code to my email at qortmdgh4141@naver.com?** 

Your assistance would be immensely appreciated.

**Comment by seohongpark** [comment]
Sure, I just sent an instruction to the email.
