### ISSUE TITLE
How to evaluate the algorithm after training?

### ISSUE THREAD

**Issue by Bxliang868** [seohongpark/HIQL#5]
Hi,
I can't find the evaluate.py file to evaluate the algorithm after training!  in Appendix D1: "At test time, to specify a goal g for the policy, we set the first two state dimensions (which correspond to the x-y coordinates) to the target goal given by the environment and the remaining proprioceptive state dimensions to those of the first observation in the dataset. "

**Comment by seohongpark** [comment]
Hi 007lbx, [here](https://github.com/seohongpark/HIQL/blob/master/jaxrl_m/evaluation.py) is the evaluation file.
