### ISSUE TITLE
a question about the bug in the iql.py

### ISSUE THREAD

**Issue by Bxliang868** [seohongpark/HIQL#7]
Dear Authors:

I want to ask a question about the bug in the iql.py , i.e., 
TypeError: create_learner() missing 1 required positional argument: 'value_def', This problem arises when I train the iql algorithm.

Your assistance would be immensely appreciated.

**Comment by seohongpark** [comment]
Hi 007lbx,

For GCIQL, we recommend using the command provided in the README file (which uses `hiql.py` not `iql.py`). Another option is to use our newest (and much cleaner) implementation available at https://github.com/seohongpark/ogbench.
