### ISSUE TITLE
Request for Roboverse Task Code in HIQL Algorithm

### ISSUE THREAD

**Issue by zhyaoch** [seohongpark/HIQL#8]
Hi,  Dr. Park

I recently read your published paper entitled "HIQL: Offline Goal-Conditioned RL with Latent States as Actions" and I found it to be one of the most inspiring articles among all the papers I have read. 

I am currently conducting research on Offline Goal-conditioned RL, and your paper is closely related to my work. I would be extremely grateful if you could kindly share the code related to the Roboverse task in the HIQL algorithm.

Thank you for your time and for making such an impactful contribution to this field. Looking forward to your response!

**Comment by seohongpark** [comment]
Hi, for the Roboverse task, we used the same environment and datasets as [this paper](https://chongyi-zheng.github.io/stable_contrastive_rl/), and please refer to that repository for the instructions.

By the way, we have recently released a new benchmark designed for offline goal-conditioned RL ([OGBench](https://seohong.me/projects/ogbench/)), including more diverse tasks and much cleaner re-implementations of offline GCRL methods, so this benchmark might be of interest to you as well.
