### ISSUE TITLE
Why use base_observation as obs_goal?

### ISSUE THREAD

**Issue by lihaomin1010** [seohongpark/HIQL#9]
In evaluate_with_trajectories(), obs_goal which is represent the final goal in different environments, but why it products from the base_observation which represent the beginning of trajectory?

**Comment by seohongpark** [comment]
An AntMaze state consists of 29 dimensions. The first two dimensions correspond to the $xy$ coordinates and the other dimensions correspond to the agent's proprioceptive states (e.g., joint angles). We took the proprioceptive states from `base_observation` (which can be any arbitrary valid state -- we simply use the first state in the dataset) and set the $xy$ coordinates to the actual goal: https://github.com/seohongpark/HIQL/blob/master/jaxrl_m/evaluation.py#L86.
